fix: fixed send script

diff --git a/bin/backup b/bin/backup
--- a/bin/backup
+++ b/bin/backup
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
 set -e
+trap 'exit 1' SIGINT
 
 DEBUG=${DEBUG:-''}
 [ -n "${DEBUG}" ] && set -x
@@ -8,12 +9,38 @@ DEBUG=${DEBUG:-''}
 # set SCRIPT_PATH
 SCRIPT_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && pwd)"
 
-SRC=${1:-''}
-DST=${2:-''}
-RSYNCOPTS="${RSYNCOPTS:-""}"
+CRONTYPE=${1:-''}
+SRC=${2:-''}
+DST_SNAP=${3:-''}
+DST_SEND=${4:-''}
+DST_REMOTE=${5:-''}
+DST_REMOTE_BACKUPDIR=${6:-''}
+VPN_CONF=${7:-''}
 
-# check if src is btrfs volume, fails and stops the script if not
-/bin/btrfs subvolume show $SRC
+# run local backup
+EXITCODE=1
+ATTEMPT=1
+while [ ${EXITCODE} -ne 0 ] && [ ${ATTEMPT} -le 3 ]
+do
+  set +e
+  ${SCRIPT_PATH}/sendrecv ${DST_SNAP} ${DST_SEND} ${CRONTYPE}
+  EXITCODE=$?
+  set -e
+  [ ${EXITCODE} -ne 0 ] && echo "sendrecv failed, trying again (${ATTEMPT}/3)." 1>&2
+  ATTEMPT=$[ATTEMPT+1]
+done
+[ ${EXITCODE} -ne 0 ] && exit 1
 
-echo "Backup to $DST"
-/usr/bin/rsync --archive --delete $RSYNCOPTS "${SRC}" "${DST}"
+# run remote backup
+EXITCODE=1
+ATTEMPT=1
+while [ ${EXITCODE} -ne 0 ] && [ ${ATTEMPT} -le 3 ]
+do
+  set +e
+  ${SCRIPT_PATH}/backup-remote ${SRC} ${DST_REMOTE} ${DST_REMOTE_BACKUPDIR} ${VPN_CONF}
+  EXITCODE=$?  
+  set -e
+  [ ${EXITCODE} -ne 0 ] && echo "backup-remote failed, trying again (${ATTEMPT}/3)." 1>&2
+  ATTEMPT=$[ATTEMPT+1]
+done
+[ ${EXITCODE} -ne 0 ] && exit 1
diff --git a/bin/backup-remote b/bin/backup-remote
--- a/bin/backup-remote
+++ b/bin/backup-remote
@@ -20,11 +20,11 @@ RSYNCOPTS="${RSYNCOPTS:-""}"
 
 if [ -n "${VPN_CONF}" ] && [ $(ping -c 1 ${DST_HOST} > /dev/null; echo $?) -ne 0 ]
 then
-  echo "Connecting to VPN (Host: ${DST_HOST})"
+  echo "Cannot ping Host, connecting to VPN (Host: ${DST_HOST})" 1>&2
   /usr/sbin/vpnc ${VPN_CONF}
 fi
 
-${SCRIPT_PATH}/backup ${SRC} ${DST_REMOTE}
+${SCRIPT_PATH}/backup-rsync ${SRC} ${DST_REMOTE}
 
 # remove locally deleted files on remote after 90 days
 [ -n "${DST_REMOTE_BACKUPDIR}" ] && ssh ${DST_USER}@${DST_HOST} find ${DST_REMOTE_BACKUPDIR} -maxdepth 1 -type d -name "??-??-??" -ctime 90 -exec "rm -rf '{}' \;"
diff --git a/bin/sendrecv b/bin/sendrecv
--- a/bin/sendrecv
+++ b/bin/sendrecv
@@ -24,7 +24,7 @@ do
       echo "Sending incremental snapshot '${SNAPSHOT}' with parent '${PARENT}'."
       btrfs send -p "${DST_SNAP%/}/${PARENT}" "${DST_SNAP%/}/${SNAPSHOT}" | btrfs receive "${DST_SEND%/}/" \
         || {
-          echo "ERROR: btrfs receive failed, trying to clean up"
+          echo "ERROR: btrfs receive failed, trying to clean up" 1>&2
           [ -d ${DST_SEND%/}/${SNAPSHOT} ] && ${SCRIPT_PATH}/snapshot-delete "${DST_SEND%/}/${SNAPSHOT}" \
             || [ -d ${DST_SEND%/}/${PARENT} ] &&  ${SCRIPT_PATH}/snapshot-delete "${DST_SEND%/}/${PARENT}"
           exit 1
@@ -39,9 +39,9 @@ do
         }
     fi
     echo "Verifying sent snapshot"
-    if [ -z "$(btrfs subvoluem show "${DST_SEND%/}/${SNAPSHOT}" | grep readonly)" ]
+    if [ -z "$(btrfs subvolume show "${DST_SEND%/}/${SNAPSHOT}" | grep readonly)" ]
     then
-      echo "ERROR: Sent snapshot is not readonly, deleting it"
+      echo "ERROR: Sent snapshot is not readonly, deleting it" 1>&2
       ${SCRIPT_PATH}/snapshot-delete "${DST_SEND%/}/${SNAPSHOT}"
     fi
   fi
