updates

diff --git a/bin/backup-remote b/bin/backup-remote
--- a/bin/backup-remote
+++ b/bin/backup-remote
@@ -13,10 +13,10 @@ DEBUG=${DEBUG:-''}
 # set BASE_PATH
 BASE_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd .. && pwd)"
 
-SRC=${1:-''}
-DST_REMOTE=${2:-''}
-DST_REMOTE_BACKUPDIR=${3:-''}
-VPN_CONF=${4:-''}
+SRC="${1:-''}"
+DST_REMOTE="${2:-''}"
+DST_REMOTE_BACKUPDIR="${3:-''}"
+VPN_CONF="${4:-''}"
 DST_USER="$(echo "${DST_REMOTE}" | cut -d@ -f1)"
 DST_HOST="$(echo "${DST_REMOTE}" | cut -d@ -f2 | cut -d: -f1)"
 RSYNCOPTS="${RSYNCOPTS:-""}"
@@ -29,7 +29,7 @@ function teardown {
   flock --unlock 200
 }
 
-exec 200>${BASE_PATH}/lock/backup-remote.lock
+exec 200>"${BASE_PATH}/lock/backup-remote.lock"
 flock -n 200 || exit 7
 echo $$ 1>&200
 
@@ -42,16 +42,16 @@ fi
 
 if [ -n "${VPN_CONF}" ] && [ $(ping -W 5 -c 1 ${DST_HOST} > /dev/null; echo $?) -ne 0 ]
 then
-  echo "Cannot ping Host, connecting to VPN (Host: ${DST_HOST})" 1>&2
-  /usr/sbin/vpnc-connect ${VPN_CONF}
+  echo "Cannot ping Host, trying to connect to VPN (Host: ${DST_HOST})" 1>&2
+  /usr/sbin/vpnc-connect ${VPN_CONF} || echo "Failed to connect to VPN, already connected?" 1>&2
 fi
 
-RSYNCOPTS="${RSYNCOPTS} --partial --compress" ${BASE_PATH}/bin/backup-rsync ${SRC} ${DST_REMOTE}
+RSYNCOPTS="${RSYNCOPTS} --partial --compress --no-inc-recursive " ${BASE_PATH}/bin/backup-rsync "${SRC}" "${DST_REMOTE}"
 
 # remove locally deleted files on remote after 90 days
 [ -n "${DST_REMOTE_BACKUPDIR}" ] \
   && ssh ${DST_USER}@${DST_HOST} \
-    find ${DST_REMOTE_BACKUPDIR} -mindepth 1 -maxdepth 1 -type d -ctime 90 -exec "echo Deleting remote backup directory '{}' \;" -exec "rm -rf '{}' \;"
+    find "${DST_REMOTE_BACKUPDIR}" -mindepth 1 -maxdepth 1 -type d -ctime 90 -exec "echo Deleting remote backup directory '{}' \;" -exec "rm -rf '{}' \;"
 
 # grep itself is listed in top, that swhy we check for 1
 if [ "$(top -cbn1 | grep ${DST_USER}@${DST_HOST} | wc -l)" -eq 1 ]
