refactor: renamed vars and some minor fixes

diff --git a/bin/log b/bin/log
--- a/bin/log
+++ b/bin/log
@@ -8,33 +8,32 @@ DEBUG=${DEBUG:-''}
 RSYNCOPTS="${RSYNCOPTS:-""}"
 
 # set some vars
-BASE_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd .. && pwd)"
-MAILTO="julian.gieseke@gmail.com"
-LOGFILE="${BASE_PATH}/log/$(basename ${1}).$(printf '%x' $(date +%s%N)).log"
-EC=0 
-SUBSCRIPT=''
+base_path="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd .. && pwd)"
+mailto="julian.gieseke@gmail.com"
+logfile_pathname="${base_path}/log/$(basename ${1}).$(printf '%x' $(date +%s%N)).log"
+exitcode=0 
+child_process=''
 
-SUBSCRIPT=${1}
-shift
+child_process="${1}" && shift
 
-# update logfilename if retry is passed as next script
-if [ "${SUBSCRIPT}" == "retry" ]
+# update logfile_pathname if retry is passed as next script
+if [ "${child_process}" == "retry" ]
 then
-  LOGFILE="${BASE_PATH}/log/$(basename ${1}).$(printf '%x' $(date +%s%N)).log"
+  logfile_pathname="${base_path}/log/$(basename ${1}).$(printf '%x' $(date +%s%N)).log"
 fi
 
 # run backup job
-echo "🎬 ${SUBSCRIPT} $@ 📅 $(date)" | tee ${LOGFILE}
-${SUBSCRIPT} "$@" 2>&1 | tee -a ${LOGFILE}
-EC=${PIPESTATUS[0]}
+echo "🎬 ${child_process} $@ 📅 $(date)" | tee ${logfile_pathname}
+${child_process} "$@" 2>&1 | tee -a ${logfile_pathname}
+exitcode=${PIPESTATUS[0]}
 
 # send mail if failed
-if [ ${EC} -ne 0 ]
+if [ ${exitcode} -ne 0 ]
 then
-  echo "❌ ${SUBSCRIPT} $@ 🛑 ${EC} 📅 $(date)"
-  echo -e "Subject: ❌ Error ${EC} in ${SUBSCRIPT} $@\n\n$(cat ${LOGFILE})" | ssmtp ${MAILTO} || cat ${LOGFILE} 1>&2
+  echo "❌ ${child_process} $@ 📅 $(date) 🛑 ${exitcode}" | tee -a ${logfile_pathname}
+  echo -e "Subject: ❌ Error ${exitcode} in ${child_process} $@\n\n$(cat ${logfile_pathname})" | ssmtp ${mailto} || cat ${logfile_pathname} 1>&2
 else
-  echo "✅ ${SUBSCRIPT} $@ 📅 $(date)" | tee -a ${LOGFILE}
+  echo "✅ ${child_process} $@ 📅 $(date)" | tee -a ${logfile_pathname}
 fi
 
-exit $EC
+exit $exitcode
diff --git a/bin/retry b/bin/retry
--- a/bin/retry
+++ b/bin/retry
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 
 # example: 
-# /mnt/.bkp/bin/retry subscript whatever subscript params are
+# /mnt/.bkp/bin/retry <child_process> <whatever child_process params are>
+# TODO: add params and add childs params after `--`
 
 set -e
 
@@ -10,21 +11,20 @@ DEBUG=${DEBUG:-''}
 
 RSYNCOPTS="${RSYNCOPTS:-""}"
 
-# set some vars
-BASE_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd .. && pwd)"
+child_process=${1} && shift
 
-SUBSCRIPT=${1}
-shift
-
-# run subscript
-RETURN=1
-ATTEMPT=1
-RETRY=3
-while [ ${RETURN} -ne 0 ] && [ ${ATTEMPT} -le ${RETRY} ]
+# run child_process
+exitcode=1
+attempt=1
+max_retries=3
+sleep_time=30
+while [ ${exitcode} -ne 0 ] && [ ${attempt} -le ${max_retries} ]
 do
-  ${SUBSCRIPT} "$@" && RETURN=0 || RETURN=$?
-  [ ${RETURN} -ne 0 ] && echo "${SUBSCRIPT} failed (exit ${RETURN}), trying again in 30s (${ATTEMPT}/3)." 1>&2 && sleep 30
-  ATTEMPT=$[ATTEMPT+1]
+  ${child_process} "$@" && exitcode=0 || exitcode=$?
+  [ ${exitcode} -ne 0 ] \
+    && echo "${child_process} failed (exit ${exitcode}), trying again in ${sleep_time}s (${attempt}/${max_retries})." 1>&2 \
+    && sleep ${sleep_time}
+  attempt=$[attempt+1]
 done
 
-exit $RETURN
+exit $exitcode
diff --git a/bin/snapshot-create b/bin/snapshot-create
--- a/bin/snapshot-create
+++ b/bin/snapshot-create
@@ -8,29 +8,26 @@ set -e
 DEBUG=${DEBUG:-''}
 [ -n "${DEBUG}" ] && set -x
 
-SRC=${1:-''}
-if [ -z "${SRC}" ]
+src_path=${1:-''}
+if [ -z "${src_path}" ]
 then
-  echo "ERROR: No \$SRC given." 2>&1
+  echo "ERROR: No \$src_path given." 2>&1
   exit 1
 fi
 
-DST=${2:-''}
-if [ -z "${DST}" ]
+dst_path=${2:-''}
+if [ -z "${dst_path}" ]
 then
-  echo "ERROR: No \$DST given." 2>&1
+  echo "ERROR: No \$dst_path given." 2>&1
   exit 1
 fi
 
-BASE_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd .. && pwd)"
+base_path="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd .. && pwd)"
 
-JOBTYPE=$(${BASE_PATH}/bin/get-jobtype ${DST})
-KEEPDAYS=$(${BASE_PATH}/bin/get-keepdays ${JOBTYPE})
+snapshot_name="$(date '+%F-%H-%M-%S')-$(${base_path}/bin/jobtype ${dst_path})"
+[ -d "${dst_path%/}/${snapshot_name}" ] && ( echo "ERROR: '${snapshot_name}' already exists."; exit 1 )
 
-SNAPSHOTNAME="$(date '+%F-%H-%M-%S')-${JOBTYPE}"
-[ -d "${DST%/}/${SNAPSHOTNAME}" ] && ( echo "ERROR: '${SNAPSHOTNAME}' already exists."; exit 1 )
+# update timestamp for find commands - this also fails if src_path is ""
+touch ${src_path}
 
-# update timestamp for find commands - this also fails if SRC is ""
-touch ${SRC}
-
-btrfs subvolume snapshot -r "${SRC}" "${DST%/}/${SNAPSHOTNAME}"
+btrfs subvolume snapshot -r "${src_path}" "${dst_path%/}/${snapshot_name}"
