refactor: moved some files

diff --git a/inc/header b/inc/header
--- a/inc/header
+++ b/inc/header
@@ -5,10 +5,12 @@ set -e
 DEBUG=${DEBUG:-''}
 [ -n "${DEBUG}" ] && set -x
 
-lockfile -600 -r5  "${SCRIPT_PATH}/bkp.${JOBNAME}.lock"
-trap '[ $? -ne 0 ] && echo "❌ Stopped with errors."; rm -f "${SCRIPT_PATH}/bkp.${JOBNAME}.lock"; trap - EXIT' EXIT SIGINT
-echo -e "\n🚛 Starting at $(date)"
+LOCKFILE="${SCRIPT_PATH}/lock/${JOBNAME}.lock"
+lockfile -600 -r5  "${LOCKFILE}"
+echo $$ > "${LOCKFILE}"
+trap '[ $? -ne 0 ] && echo "❌ Stopped with errors at $(date)."; rm -f "${LOCKFILE}"; trap - EXIT' EXIT SIGINT
 
+echo -e "\n🚛 Starting at $(date)"
 
 function displaytime {
 
